modLoader="javafml"
loaderVersion="[31,)"
license="All rights reserved"

[[mods]]
modId="firewalker"
version="1.0"
displayName="FireWalker"
updateJSONURL="http://myurl.me"
displayURL="http://https://github.com/chrisoliver345/Fire-Walker-1.16/"
logoFile="logo.png"
credits="Thanks to Chris"
authors="Chris" #optional
description="Mod for Minecraft 1.16.3"

[[dependencies.firewalker]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.firewalker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
