modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="firewalker"
version="1.0"
displayName="Whiteridge"
updateJSONURL="http://myurl.me"
displayURL="http://example.com/"
logoFile="enchantplus.png"
credits="Thanks to Chris"
authors="Chris" #optional
description="Mod for Minecraft 1.15"

[[dependencies.firewalker]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.firewalker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
